# Generated by Django 4.0.4 on 2022-08-27 15:26

from django.db import migrations, models
import django.utils.timezone
import wasteclassification_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteclassification_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=wasteclassification_app.models.path_and_rename),
            preserve_default=False,
        ),
    ]
