# Generated by Django 4.0.4 on 2022-08-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteclassification_app', '0002_remove_file_file_file_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Filee',
        ),
    ]
